version: '3.8'

services:
  db:
    image: postgres:13.2
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: always
    ports:
      - 5545:5432
    volumes:
      - postgres_data_pack:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build: ./backend
    working_dir: /backend
    command: bash -c "alembic downgrade base && python script.py && alembic upgrade head && python full_base.py && exec uvicorn app.main:app --host backend --port 8000 --reload"
    volumes:
      - ./backend:/backend
    ports:
      - 8080:8000
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
  
  data_science:
    build: ./data_science
    volumes:
      - ./data_science/src:/data_science
    ports:
      - 6000:6000
    command: python app.py


volumes:
  postgres_data_pack: