"""Add models

Revision ID: c6e23a4e8bd5
Revises: 
Create Date: 2023-06-17 00:23:52.234734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6e23a4e8bd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargotype',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('carton',
    sa.Column('cartontype', sa.String(length=8), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('barcode', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('cartontype')
    )
    op.create_table('item',
    sa.Column('sku', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('a', sa.Float(), nullable=False),
    sa.Column('b', sa.Float(), nullable=False),
    sa.Column('c', sa.Float(), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('package_type', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('order',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('start_packing', sa.DateTime(), nullable=True),
    sa.Column('closed', sa.DateTime(), nullable=True),
    sa.Column('status', postgresql.ENUM('FORMING', 'PACKING', 'COMPLETED', 'CANCELLED', name='status'), nullable=True),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargoitem',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('cargotype_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['cargotype_id'], ['cargotype.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'cargotype_id', 'id')
    )
    op.create_table('ordercarton',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('carton_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['carton_id'], ['carton.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'carton_id', 'id')
    )
    op.create_table('orderitem',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'order_id', 'id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('payload',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'id')
    )
    op.create_table('usedcarton',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('carton_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['carton_id'], ['carton.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'carton_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usedcarton')
    op.drop_table('payload')
    op.drop_table('orderitem')
    op.drop_table('ordercarton')
    op.drop_table('cargoitem')
    op.drop_table('order')
    op.drop_table('item')
    op.drop_table('carton')
    op.drop_table('cargotype')
    # ### end Alembic commands ###
